name: 🎨 Template Submission
description: Submit a new template for inclusion in the repository
title: "[Template]: "
labels: ["template-submission", "enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing a new template! Please provide all the required information below.

  - type: input
    id: template-name
    attributes:
      label: Template Name
      description: What is the name of your template?
      placeholder: e.g., "Dark Mode Developer", "Retro Gaming Profile"
    validations:
      required: true

  - type: dropdown
    id: template-category
    attributes:
      label: Template Category
      description: Which category does your template belong to?
      options:
        - Minimalist
        - Developer
        - Creative
        - Gaming
        - Business
        - Animated
        - Statistics
        - New Category (specify in description)
    validations:
      required: true

  - type: textarea
    id: template-description
    attributes:
      label: Template Description
      description: Provide a detailed description of your template
      placeholder: |
        - What makes this template unique?
        - Who is the target audience?
        - What features does it include?
    validations:
      required: true

  - type: textarea
    id: key-features
    attributes:
      label: Key Features
      description: List the main features of your template
      placeholder: |
        - Feature 1
        - Feature 2
        - Feature 3
    validations:
      required: true

  - type: textarea
    id: template-code
    attributes:
      label: Template Code
      description: Paste your complete template markdown code here
      placeholder: |
        ```markdown
        # Your template code here
        ```
    validations:
      required: true

  - type: checkboxes
    id: template-checklist
    attributes:
      label: Template Quality Checklist
      description: Please confirm your template meets these requirements
      options:
        - label: Template includes customization guide
          required: true
        - label: All placeholders are clearly marked (e.g., YOUR_USERNAME)
          required: true
        - label: Template is tested and renders correctly on GitHub
          required: true
        - label: All external links and services work properly
          required: true
        - label: Template follows project style guidelines
          required: true
        - label: Template is original or properly attributed
          required: true

  - type: textarea
    id: customization-guide
    attributes:
      label: Customization Instructions
      description: Provide step-by-step instructions for customizing your template
      placeholder: |
        1. Replace [Your Name] with your actual name
        2. Update YOUR_USERNAME with your GitHub username
        3. Modify the skills section to reflect your abilities
        4. ...
    validations:
      required: true

  - type: textarea
    id: preview-images
    attributes:
      label: Preview Images
      description: Add screenshots or preview images of your template
      placeholder: |
        Drag and drop images here or paste URLs
        - Desktop view
        - Mobile view (if different)
        - Any special features

  - type: dropdown
    id: difficulty-level
    attributes:
      label: Difficulty Level
      description: How difficult is it to customize this template?
      options:
        - Easy - Basic customization only
        - Medium - Some technical knowledge required
        - Advanced - Requires good understanding of markdown/HTML
    validations:
      required: true

  - type: checkboxes
    id: contribution-agreement
    attributes:
      label: Contribution Agreement
      description: Please confirm you agree to the following
      options:
        - label: I agree to license my contribution under the MIT License
          required: true
        - label: I confirm this is my original work or properly attributed
          required: true
        - label: I'm willing to maintain and update this template if needed
          required: false

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Any additional information about your template
      placeholder: |
        - Special requirements or dependencies
        - Known issues or limitations
        - Future improvement ideas
        - Credits or acknowledgments